import type { CatalogKind, CatalogStatus, Json } from '@/lib/types'

export type SeedItem = {
  name: string
  kind?: CatalogKind
  category: string
  subcategory?: string
  producer?: string
  country?: string
  region?: string
  abv?: number
  age_statement?: string
  vintage?: number
  description: string
  tasting_notes?: string
  status?: CatalogStatus
  price_cents?: number
  hero_image_url?: string
  specs: Record<string, Json>
  media?: Array<{ kind: 'image' | 'youtube'; url: string; caption?: string }>
}

export const CATALOG: SeedItem[] = [
  // =========================================================================
  // RUM — Jamaican
  // =========================================================================
  {
    name: 'Hampden Estate 8 Year',
    category: 'Rum',
    subcategory: 'Jamaican',
    producer: 'Hampden Estate',
    country: 'Jamaica',
    region: 'Trelawny',
    abv: 46,
    age_statement: '8 Years',
    price_cents: 2200,
    description:
      'Fully tropically aged in Trelawny, from a distillery that adds nothing to anything. The wild fermentation runs for weeks, and the resulting ester load is the point rather than a side effect.',
    tasting_notes:
      'Overripe banana and pineapple skin up front, then varnish, brine and clove. Long, drying, faintly funky finish.',
    specs: {
      base_material: 'Molasses from Jamaican cane',
      still_type: 'Double-retort copper pot',
      fermentation: 'Wild / spontaneous, with dunder and muck',
      fermentation_length: 'Up to 30 days',
      distillation_proof: '~172 proof (86% ABV)',
      barrel_types: 'Ex-bourbon American oak',
      aging_length: '8 years, 100% tropical',
      aging_climate: 'Tropical (Trelawny)',
      angels_share: '~6% per year',
      additives: 'None — no sugar, no colouring',
      marque: 'OWH / LFCH blend',
      ester_count: '~400–700 g/hLPA',
      dunder: 'Yes — traditional muck pit',
      filtration: 'Non-chill filtered',
    },
  },
  {
    name: 'Appleton Estate 12 Year Rare Casks',
    category: 'Rum',
    subcategory: 'Jamaican',
    producer: 'Appleton Estate',
    country: 'Jamaica',
    region: 'Nassau Valley',
    abv: 43,
    age_statement: '12 Years',
    price_cents: 1800,
    description:
      'Joy Spence\'s blend of pot and column distillate, with every component at least twelve years old under tropical conditions.',
    tasting_notes: 'Orange peel, vanilla, cocoa and a light green-cane lift on the finish.',
    specs: {
      base_material: 'Molasses',
      still_type: 'Pot and column blend',
      fermentation: 'Cultured yeast, 30–36 hours',
      barrel_types: 'Ex-bourbon American oak',
      aging_length: 'Minimum 12 years, tropical',
      aging_climate: 'Tropical',
      angels_share: '~6% per year',
      additives: 'None declared',
      filtration: 'Chill filtered',
    },
  },
  {
    name: 'Worthy Park 109',
    category: 'Rum',
    subcategory: 'Jamaican',
    producer: 'Worthy Park Estate',
    country: 'Jamaica',
    region: 'Lluidas Vale',
    abv: 54.5,
    price_cents: 1600,
    description:
      'Unaged single-estate pot still rum at overproof strength. Everything from the cane in the field to the bottle happens inside one valley.',
    tasting_notes: 'Green olive brine, acetone, crushed cane and a hot, clean finish.',
    specs: {
      base_material: 'Estate-grown cane molasses',
      still_type: 'Forsyths double-retort copper pot',
      fermentation: 'Proprietary cultured yeast, ~30 hours',
      barrel_types: 'Unaged',
      aging_length: 'None',
      additives: 'None',
      marque: 'WPL',
      ester_count: '~60–120 g/hLPA',
      filtration: 'None',
    },
  },

  // --- Rum — Martinique ----------------------------------------------------
  {
    name: 'Rhum J.M VSOP',
    category: 'Rum',
    subcategory: 'Martinique',
    producer: 'Rhum J.M',
    country: 'Martinique',
    region: 'Macouba',
    abv: 43,
    age_statement: '4+ Years',
    price_cents: 1700,
    description:
      'Rhum agricole from volcanic soil at the foot of Mount Pelée, distilled from fresh cane juice within an hour of the harvest.',
    tasting_notes: 'Baked banana, cocoa nib, vanilla and a mineral, grassy backbone.',
    specs: {
      base_material: 'Fresh-pressed cane juice (vesou)',
      still_type: 'Single creole column, copper',
      fermentation: 'Short, 24–36 hours, indigenous yeast',
      distillation_proof: '~140 proof (70% ABV)',
      barrel_types: 'Ex-bourbon American oak',
      aging_length: 'Minimum 4 years',
      aging_climate: 'Tropical',
      aoc: 'AOC Martinique Rhum Agricole',
      cane_variety: 'Blue cane and canne rouge',
      harvest: 'Hand cut, February–June',
      additives: 'None permitted under AOC',
    },
  },
  {
    name: 'Neisson Rhum Blanc L\'Esprit 70°',
    category: 'Rum',
    subcategory: 'Martinique',
    producer: 'Neisson',
    country: 'Martinique',
    region: 'Le Carbet',
    abv: 70,
    price_cents: 1500,
    description:
      'Overproof white agricole bottled straight off the still at seventy percent. The most concentrated statement of the house style.',
    tasting_notes: 'Raw cane, white pepper, olive and an enormous grassy exhale.',
    specs: {
      base_material: 'Fresh cane juice from estate fields',
      still_type: 'Single creole column',
      fermentation: '~36 hours, natural yeast',
      distillation_proof: '140 proof (70% ABV)',
      aging_length: 'Rested in steel, 3 months minimum',
      aoc: 'AOC Martinique Rhum Agricole',
      cane_variety: 'Canne bleue',
      additives: 'None',
    },
  },

  // --- Rum — Barbados & other ----------------------------------------------
  {
    name: 'Foursquare Doorly\'s 12 Year',
    category: 'Rum',
    subcategory: 'Barbados',
    producer: 'Foursquare Distillery',
    country: 'Barbados',
    abv: 48,
    age_statement: '12 Years',
    price_cents: 1500,
    description:
      'Richard Seale\'s twelve-year blend finished in ex-Madeira casks, and a standing argument that rum needs no sugar to taste sweet.',
    tasting_notes: 'Toffee, dried apricot, oak spice, and a dry, clean finish.',
    specs: {
      base_material: 'Molasses',
      still_type: 'Twin column and double-retort pot',
      fermentation: 'Cultured yeast',
      barrel_types: 'Ex-bourbon, finished in ex-Madeira',
      aging_length: '12 years tropical',
      aging_climate: 'Tropical',
      additives: 'None — no sugar, no colouring',
      filtration: 'Non-chill filtered',
      blend_ratio: 'Pot and column blend',
    },
  },
  {
    name: 'Mount Gay Black Barrel',
    category: 'Rum',
    subcategory: 'Barbados',
    producer: 'Mount Gay Distilleries',
    country: 'Barbados',
    abv: 43,
    price_cents: 1300,
    description:
      'A double-matured Barbadian blend finished briefly in deeply charred bourbon barrels for a smokier, more assertive profile.',
    tasting_notes: 'Toasted oak, vanilla, black pepper and dried banana.',
    specs: {
      base_material: 'Molasses',
      still_type: 'Twin column and copper pot',
      barrel_types: 'Ex-bourbon, finished in heavily charred oak',
      aging_length: '3–7 years',
      aging_climate: 'Tropical',
      blend_ratio: 'Pot-forward blend',
    },
  },
  {
    name: 'El Dorado 15 Year Special Reserve',
    category: 'Rum',
    subcategory: 'Rum Other',
    producer: 'Demerara Distillers',
    country: 'Guyana',
    region: 'Demerara',
    abv: 43,
    age_statement: '15 Years',
    price_cents: 1600,
    description:
      'A blend drawing on the last wooden stills in the world, including the Port Mourant double wooden pot and the Enmore wooden Coffey.',
    tasting_notes: 'Molasses, dark chocolate, coffee and a distinctly sweet, viscous body.',
    specs: {
      base_material: 'Demerara molasses',
      still_type: 'Wooden Coffey, wooden pot, and column',
      fermentation: 'Cultured yeast',
      barrel_types: 'Ex-bourbon American oak',
      aging_length: 'Minimum 15 years',
      aging_climate: 'Tropical',
      additives: 'Sugar dosage present (~30–40 g/L)',
    },
  },

  // --- Cachaça, Clairin, other ---------------------------------------------
  {
    name: 'Avuá Cachaça Amburana',
    category: 'Rum',
    subcategory: 'Cachaça',
    producer: 'Avuá Cachaça',
    country: 'Brazil',
    region: 'Rio de Janeiro',
    abv: 40,
    age_statement: '2 Years',
    price_cents: 1400,
    description:
      'Single-estate cachaça rested in amburana, a Brazilian hardwood that gives cinnamon and vanilla far faster than oak would.',
    tasting_notes: 'Cinnamon, toasted coconut, marzipan and a warm baking-spice finish.',
    specs: {
      base_material: 'Fresh-pressed sugarcane juice',
      still_type: 'Copper alembic pot',
      fermentation: 'Wild yeast, 24 hours',
      barrel_types: 'Amburana (Brazilian hardwood)',
      aging_length: '2 years',
      cane_variety: 'Hand-cut estate cane',
      wood_type: 'Amburana cearensis',
      additives: 'None',
    },
  },
  {
    name: 'Novo Fogo Silver',
    category: 'Rum',
    subcategory: 'Cachaça',
    producer: 'Novo Fogo',
    country: 'Brazil',
    region: 'Paraná',
    abv: 40,
    price_cents: 1100,
    description:
      'Certified organic unaged cachaça from a carbon-negative distillery inside the Atlantic rainforest.',
    tasting_notes: 'Green apple, banana leaf, cut grass and a clean citrus finish.',
    specs: {
      base_material: 'Organic fresh cane juice',
      still_type: 'Copper pot',
      fermentation: 'Natural yeast, 20–24 hours',
      aging_length: 'Rested in stainless, 1 year',
      additives: 'None',
    },
  },
  {
    name: 'Clairin Sajous',
    category: 'Rum',
    subcategory: 'Clairin',
    producer: 'Chelo (Clairin Sajous)',
    country: 'Haiti',
    region: 'Saint-Michel-de-l\'Attalaye',
    abv: 56.5,
    price_cents: 1600,
    description:
      'Organic Haitian cane, wild fermented with nothing added, distilled in a single creole column and bottled unaged.',
    tasting_notes: 'Olive brine, wet stone, green banana and a searing, mineral finish.',
    specs: {
      base_material: 'Fresh cane juice',
      still_type: 'Single creole column',
      fermentation: 'Wild — no added yeast',
      fermentation_length: '5–7 days',
      terroir: 'Saint-Michel-de-l\'Attalaye, 400m',
      cane_variety: 'Cristalline, Madam Mesyeu',
      wild_yeast: 'Yes',
      aging_length: 'Unaged',
      additives: 'None',
    },
  },
  {
    name: 'Clairin Vaval',
    category: 'Rum',
    subcategory: 'Clairin',
    producer: 'Distillerie Vaval',
    country: 'Haiti',
    region: 'Cavaillon',
    abv: 54.5,
    price_cents: 1600,
    description:
      'Faubert Vaval\'s clairin from Hawaii Blanche cane, fermented on its own wild yeasts in open wooden tanks.',
    tasting_notes: 'Lime pith, hay, black pepper and a long saline finish.',
    specs: {
      base_material: 'Fresh cane juice',
      still_type: 'Small creole column',
      fermentation: 'Wild, in open wood',
      fermentation_length: '5 days',
      terroir: 'Cavaillon, southern Haiti',
      cane_variety: 'Hawaii Blanche',
      wild_yeast: 'Yes',
      aging_length: 'Unaged',
    },
  },
  {
    name: 'By The Dutch Batavia Arrack',
    category: 'Rum',
    subcategory: 'Sugar Distillate Other',
    producer: 'By The Dutch',
    country: 'Indonesia',
    region: 'Java',
    abv: 48,
    price_cents: 1400,
    description:
      'The spirit at the root of eighteenth-century punch: Javanese cane molasses fermented with red rice cakes and Java\'s wild yeasts.',
    tasting_notes: 'Sandalwood, dried mango, sourdough and a dusty, exotic finish.',
    specs: {
      base_material: 'Sugarcane molasses with fermented red rice',
      still_type: 'Traditional Javanese pot',
      fermentation: 'Wild yeasts, red rice cake starter',
      barrel_types: 'Teak vats',
      aging_length: '8 years in Java, then blended',
      additives: 'None',
    },
  },

  // =========================================================================
  // WHISKEY — Bourbon
  // =========================================================================
  {
    name: 'Wild Turkey Rare Breed',
    category: 'Whiskey',
    subcategory: 'Bourbon',
    producer: 'Wild Turkey',
    country: 'United States',
    region: 'Kentucky',
    abv: 58.4,
    price_cents: 1600,
    description:
      'A barrel-proof batching of six, eight, and twelve-year stocks, built on the lowest barrel entry proof in Kentucky.',
    tasting_notes: 'Toasted oak, orange marmalade, tobacco leaf, and a long spicy heat.',
    specs: {
      mash_bill: '75% corn, 13% rye, 12% malted barley',
      grain_source: 'Kentucky and Indiana',
      yeast: 'Proprietary strain, in use since the 1950s',
      fermentation: '72 hours, open-top fermenters',
      still_type: 'Column plus doubler',
      distillation_proof: '~115–125 proof off the still',
      entry_proof: '107 proof',
      barrel_types: 'New charred American white oak',
      char_level: '#4 "alligator" char',
      warehouse: 'Multi-story wooden rickhouses, Tyrone',
      aging_length: '6, 8 and 12 year blend',
      batch_type: 'Small batch, barrel proof',
      filtration: 'Non-chill filtered',
    },
  },
  {
    name: 'Four Roses Single Barrel',
    category: 'Whiskey',
    subcategory: 'Bourbon',
    producer: 'Four Roses',
    country: 'United States',
    region: 'Kentucky',
    abv: 50,
    price_cents: 1500,
    description:
      'Always the OBSV recipe — the high-rye mash bill with the delicate fruit yeast — drawn from a single barrel.',
    tasting_notes: 'Ripe pear, clove, dark cherry and a dry, spicy oak finish.',
    specs: {
      mash_bill: '60% corn, 35% rye, 5% malted barley (Mash B)',
      yeast: 'V strain — delicate fruit',
      fermentation: '~4 days',
      still_type: 'Column plus doubler',
      entry_proof: '120 proof',
      barrel_types: 'New charred American oak',
      char_level: '#4',
      warehouse: 'Single-story rickhouses, Cox\'s Creek',
      aging_length: '7–9 years',
      batch_type: 'Single barrel',
      filtration: 'Non-chill filtered',
    },
  },
  {
    name: 'Old Forester 1920 Prohibition Style',
    category: 'Whiskey',
    subcategory: 'Bourbon',
    producer: 'Brown-Forman (Old Forester)',
    country: 'United States',
    region: 'Kentucky',
    abv: 57.5,
    price_cents: 1500,
    description:
      'Built to replicate the barrel strength of medicinal whiskey bottled during Prohibition, when Old Forester held one of ten permits.',
    tasting_notes: 'Dark caramel, cinnamon, char and stewed dark fruit.',
    specs: {
      mash_bill: '72% corn, 18% rye, 10% malted barley',
      fermentation: '~4 days',
      still_type: 'Column plus doubler',
      entry_proof: '125 proof',
      barrel_types: 'New charred American oak, made in-house',
      char_level: '#4',
      warehouse: 'Heat-cycled, middle floors',
      aging_length: '~5 years',
      batch_type: 'Small batch',
      filtration: 'Non-chill filtered',
    },
  },
  {
    name: 'Buffalo Trace Kentucky Straight Bourbon',
    category: 'Whiskey',
    subcategory: 'Bourbon',
    producer: 'Buffalo Trace Distillery',
    country: 'United States',
    region: 'Kentucky',
    abv: 45,
    price_cents: 1100,
    description:
      'The flagship of Mash Bill #1 — the low-rye recipe that also underpins Eagle Rare and Stagg.',
    tasting_notes: 'Vanilla, brown sugar, mint and a soft, sweet finish.',
    specs: {
      mash_bill: 'Mash Bill #1 — low rye (~10%)',
      fermentation: '~3–5 days',
      still_type: 'Column plus doubler',
      entry_proof: '125 proof',
      barrel_types: 'New charred American oak',
      char_level: '#4',
      warehouse: 'Brick and wood rickhouses, Frankfort',
      aging_length: '8–9 years',
      batch_type: 'Small batch',
    },
  },

  // --- Whiskey — Rye --------------------------------------------------------
  {
    name: 'Rittenhouse Rye Bottled-in-Bond',
    category: 'Whiskey',
    subcategory: 'Rye',
    producer: 'Heaven Hill',
    country: 'United States',
    region: 'Kentucky',
    abv: 50,
    age_statement: '4 Years',
    price_cents: 1100,
    description:
      'A barely-legal rye at bonded strength — one distillery, one season, four years minimum, one hundred proof. The bar\'s default rye for a reason.',
    tasting_notes: 'Baking spice, honey, dill and a firm peppery finish.',
    specs: {
      mash_bill: '51% rye, 37% corn, 12% malted barley',
      fermentation: '~4 days',
      still_type: 'Column plus doubler',
      entry_proof: '125 proof',
      barrel_types: 'New charred American oak',
      char_level: '#3',
      aging_length: 'Minimum 4 years',
      batch_type: 'Bottled-in-Bond',
    },
  },
  {
    name: 'WhistlePig 10 Year Rye',
    category: 'Whiskey',
    subcategory: 'Rye',
    producer: 'WhistlePig',
    country: 'United States',
    region: 'Vermont',
    abv: 50,
    age_statement: '10 Years',
    price_cents: 1800,
    description:
      'A 100% rye mash bill sourced from Canada and finished on the Vermont farm — the bottling that started the modern rye revival.',
    tasting_notes: 'Caraway, orange oil, mint and a long, dry rye-bread finish.',
    specs: {
      mash_bill: '100% rye',
      still_type: 'Column',
      barrel_types: 'New charred American oak',
      aging_length: '10 years',
      batch_type: 'Small batch',
      filtration: 'Non-chill filtered',
    },
  },
  {
    name: 'Michter\'s US*1 Single Barrel Rye',
    category: 'Whiskey',
    subcategory: 'Rye',
    producer: 'Michter\'s',
    country: 'United States',
    region: 'Kentucky',
    abv: 42.4,
    price_cents: 1400,
    description:
      'Filled at an unusually low 103 entry proof, which pulls less wood tannin and more sweetness out of the barrel.',
    tasting_notes: 'Butterscotch, citrus peel, gentle rye spice and a soft close.',
    specs: {
      mash_bill: 'Rye-forward, undisclosed proportions',
      entry_proof: '103 proof',
      barrel_types: 'New charred American oak, air-dried 18+ months',
      warehouse: 'Heat-cycled',
      aging_length: 'Undisclosed, single barrel',
      batch_type: 'Single barrel',
      filtration: 'Non-chill filtered',
    },
  },

  // --- Whiskey — American other, Japanese ----------------------------------
  {
    name: 'Balcones Baby Blue',
    category: 'Whiskey',
    subcategory: 'American Whiskey Other',
    producer: 'Balcones Distilling',
    country: 'United States',
    region: 'Texas',
    abv: 46,
    price_cents: 1300,
    description:
      'The first Texas whiskey since Prohibition, made from roasted Hopi blue corn rather than dent corn.',
    tasting_notes: 'Toasted corn tortilla, hazelnut, honey and a nutty finish.',
    specs: {
      mash_bill: '100% roasted Hopi blue corn',
      fermentation: 'Open-top, ~5 days',
      still_type: 'Copper pot',
      barrel_types: 'Used and new American oak',
      aging_length: '~18–24 months (Texas heat)',
      filtration: 'Non-chill filtered',
    },
  },
  {
    name: 'Westward American Single Malt',
    category: 'Whiskey',
    subcategory: 'American Whiskey Other',
    producer: 'Westward Whiskey',
    country: 'United States',
    region: 'Oregon',
    abv: 45,
    price_cents: 1600,
    description:
      'Brewed like a Pacific Northwest ale before it is ever distilled — ale yeast, a full fermentation, and no peat anywhere.',
    tasting_notes: 'Malt loaf, stone fruit, cocoa and a soft brewery-sweet finish.',
    specs: {
      mash_bill: '100% two-row Pacific Northwest barley',
      yeast: 'American ale yeast',
      fermentation: '5–6 days, cool',
      still_type: 'Copper pot, double distilled',
      barrel_types: 'New lightly charred American oak',
      aging_length: 'Minimum 2 years',
      filtration: 'Non-chill filtered',
    },
  },
  {
    name: 'Nikka Coffey Grain',
    category: 'Whiskey',
    subcategory: 'Japanese',
    producer: 'Nikka Whisky',
    country: 'Japan',
    region: 'Miyagi',
    abv: 45,
    price_cents: 1700,
    description:
      'Corn-based grain whisky from Nikka\'s 1963 Coffey stills — a still design abandoned almost everywhere else for being inefficient.',
    tasting_notes: 'Candied orange, coconut, vanilla custard and a syrupy sweetness.',
    specs: {
      mash_bill: 'Predominantly corn with malted barley',
      still_type: 'Coffey continuous still (1963)',
      distillation_proof: 'Lower than modern column, retains texture',
      barrel_types: 'Ex-bourbon American oak',
      aging_length: 'No age statement',
      jsla: 'Yes',
    },
  },
  {
    name: 'Hakushu 12 Year',
    category: 'Whiskey',
    subcategory: 'Japanese',
    producer: 'Suntory',
    country: 'Japan',
    region: 'Yamanashi',
    abv: 43,
    age_statement: '12 Years',
    price_cents: 3200,
    description:
      'Distilled in a forest distillery at 700 metres in the Southern Japanese Alps, with a light hand on the peat.',
    tasting_notes: 'Green apple, cucumber, pine needle and a wisp of smoke.',
    specs: {
      mash_bill: '100% malted barley, lightly peated',
      peat_ppm: 'Lightly peated component',
      fermentation: 'Wooden washbacks',
      still_type: 'Copper pot, multiple shapes',
      barrel_types: 'American, Spanish and Japanese oak',
      aging_length: '12 years',
      mizunara: 'Component casks',
      jsla: 'Yes',
      filtration: 'Chill filtered',
    },
  },

  // --- Whiskey — Scotch -----------------------------------------------------
  {
    name: 'Lagavulin 16 Year',
    category: 'Whiskey',
    subcategory: 'Scotch',
    producer: 'Lagavulin',
    country: 'Scotland',
    region: 'Islay',
    abv: 43,
    age_statement: '16 Years',
    price_cents: 2400,
    description:
      'Islay\'s benchmark. Distilled slower than almost anything else in Scotland — the spirit still run takes over five hours.',
    tasting_notes: 'Iodine, wood smoke, seaweed, dried fig and an enormous, tarry finish.',
    specs: {
      scotch_region: 'Islay',
      malt_type: 'Single malt',
      peat_ppm: '~35 ppm phenols',
      malting: 'Port Ellen maltings',
      fermentation: '55+ hours',
      still_type: 'Copper pot, 2 wash and 2 spirit',
      still_shape: 'Pear-shaped, slow run',
      distillation_proof: 'Cut around 72% ABV',
      barrel_types: 'Refill American and European oak',
      aging_length: '16 years',
      filtration: 'Chill filtered',
      coloring: 'Yes (E150)',
    },
  },
  {
    name: 'Springbank 10 Year',
    category: 'Whiskey',
    subcategory: 'Scotch',
    producer: 'Springbank',
    country: 'Scotland',
    region: 'Campbeltown',
    abv: 46,
    age_statement: '10 Years',
    price_cents: 2200,
    description:
      'Two-and-a-half times distilled, floor malted on site, and bottled without chill filtration or colouring — a distillery that does everything the slow way.',
    tasting_notes: 'Brine, damp wool, pear, light smoke and an oily, coating texture.',
    specs: {
      scotch_region: 'Campbeltown',
      malt_type: 'Single malt',
      peat_ppm: '~12–15 ppm',
      malting: '100% floor malted on site',
      fermentation: 'Boby mill, 72–110 hours',
      still_type: 'Copper pot — 1 wash, 2 spirit',
      distillations: '2.5 times',
      barrel_types: '60% ex-bourbon, 40% ex-sherry',
      aging_length: '10 years',
      filtration: 'Non-chill filtered',
      coloring: 'None',
    },
  },
  {
    name: 'Glenfarclas 105 Cask Strength',
    category: 'Whiskey',
    subcategory: 'Scotch',
    producer: 'Glenfarclas',
    country: 'Scotland',
    region: 'Speyside',
    abv: 60,
    price_cents: 2000,
    description:
      'One of the original cask-strength bottlings, at 105 British proof, from a distillery that still direct-fires its stills with gas.',
    tasting_notes: 'Christmas cake, raisin, orange peel and a big sherried heat.',
    specs: {
      scotch_region: 'Speyside',
      malt_type: 'Single malt',
      peat_ppm: 'Unpeated',
      fermentation: '48+ hours, stainless washbacks',
      still_type: 'Direct gas-fired copper pot — largest in Speyside',
      barrel_types: 'Ex-oloroso sherry, European oak',
      aging_length: 'No age statement, ~8–10 years',
      filtration: 'Non-chill filtered',
      coloring: 'None',
    },
  },

  // --- Whiskey — Irish, international --------------------------------------
  {
    name: 'Redbreast 12 Year',
    category: 'Whiskey',
    subcategory: 'Irish',
    producer: 'Irish Distillers (Midleton)',
    country: 'Ireland',
    region: 'County Cork',
    abv: 40,
    age_statement: '12 Years',
    price_cents: 1600,
    description:
      'The standard-bearer for single pot still Irish whiskey — a mixed mash of malted and unmalted barley, triple distilled.',
    tasting_notes: 'Marzipan, dried apricot, clove and a creamy, spicy body.',
    specs: {
      mash_bill: 'Malted and unmalted barley (single pot still)',
      pot_still_type: 'Single pot still',
      distillations: 'Triple distilled',
      still_type: 'Copper pot',
      barrel_types: 'Ex-bourbon and ex-oloroso sherry',
      aging_length: '12 years',
      filtration: 'Chill filtered',
    },
  },
  {
    name: 'Green Spot',
    category: 'Whiskey',
    subcategory: 'Irish',
    producer: 'Irish Distillers (Midleton)',
    country: 'Ireland',
    region: 'County Cork',
    abv: 40,
    price_cents: 1700,
    description:
      'A bonded whiskey originally commissioned by Dublin grocers Mitchell & Son, who once matured it in their own cellars.',
    tasting_notes: 'Orchard fruit, barley sugar, mint and a fresh, bright finish.',
    specs: {
      mash_bill: 'Malted and unmalted barley',
      pot_still_type: 'Single pot still',
      distillations: 'Triple distilled',
      barrel_types: 'Ex-bourbon and ex-sherry',
      aging_length: '7–10 years',
    },
  },
  {
    name: 'Amrut Fusion',
    category: 'Whiskey',
    subcategory: 'International Whiskey Other',
    producer: 'Amrut Distilleries',
    country: 'India',
    region: 'Bangalore',
    abv: 50,
    price_cents: 1900,
    description:
      'Indian and peated Scottish barley, mashed together and matured at 900 metres, where the angel\'s share runs four times Scotland\'s rate.',
    tasting_notes: 'Cocoa, dried fruit, smoke and a big, warming spice.',
    specs: {
      mash_bill: '75% Indian barley, 25% peated Scottish barley',
      peat_ppm: '~24 ppm on the Scottish portion',
      still_type: 'Copper pot',
      barrel_types: 'New and ex-bourbon American oak',
      aging_length: '~4 years tropical',
      filtration: 'Non-chill filtered',
    },
  },

  // =========================================================================
  // GIN
  // =========================================================================
  {
    name: 'Tanqueray No. TEN',
    category: 'Gin',
    producer: 'Tanqueray',
    country: 'Scotland',
    abv: 47.3,
    price_cents: 1300,
    description:
      'Made in a small still nicknamed "Tiny Ten" using whole fresh citrus rather than dried peel — unusual, and expensive, at scale.',
    tasting_notes: 'Grapefruit, lime, chamomile and a clean juniper spine.',
    specs: {
      botanicals:
        'Juniper, coriander, angelica, liquorice, whole white grapefruit, whole lime, whole orange, chamomile',
      base_spirit: 'Neutral grain',
      infusion_method: 'Maceration then pot distillation, four times',
      still_type: 'Copper pot ("Tiny Ten")',
      style: 'Contemporary / citrus-forward',
    },
  },
  {
    name: 'Sipsmith V.J.O.P.',
    category: 'Gin',
    producer: 'Sipsmith',
    country: 'England',
    abv: 57.7,
    price_cents: 1500,
    description:
      '"Very Junipery Over Proof" — juniper is added three separate times, at three stages, in pursuit of a single idea.',
    tasting_notes: 'Pine, resin, black pepper and a long, dry, unapologetic juniper finish.',
    specs: {
      botanicals: 'Juniper (tripled), coriander, angelica, orris, liquorice, orange, lemon, cassia, cinnamon, almond',
      base_spirit: 'Neutral grain',
      infusion_method: 'Triple juniper — macerated, boosted, and vapour infused',
      still_type: 'Copper pot ("Prudence")',
      style: 'Navy strength London Dry',
    },
  },
  {
    name: 'Monkey 47 Schwarzwald Dry Gin',
    category: 'Gin',
    producer: 'Monkey 47',
    country: 'Germany',
    region: 'Black Forest',
    abv: 47,
    price_cents: 1700,
    description:
      'Forty-seven botanicals, including lingonberry, and a rest in earthenware vessels before bottling.',
    tasting_notes: 'Lingonberry, pine, cardamom and a dense, layered herbal finish.',
    specs: {
      botanicals: '47 botanicals, including lingonberry, spruce, bramble leaf, elderflower',
      base_spirit: 'Molasses neutral',
      infusion_method: 'Maceration, then gentle pot distillation',
      still_type: 'Copper pot',
      aging_length: 'Rested 3 months in earthenware',
      style: 'Dry gin',
    },
  },
  {
    name: 'Hayman\'s Old Tom Gin',
    category: 'Gin',
    producer: 'Hayman\'s of London',
    country: 'England',
    abv: 41.4,
    price_cents: 1200,
    description:
      'The style that sits between genever and London Dry, and the bottle that made Martinez and Tom Collins possible again.',
    tasting_notes: 'Sweet juniper, liquorice, orange peel and a rounder, softer body.',
    specs: {
      botanicals: 'Juniper, coriander, angelica, liquorice, orris, cassia, cinnamon, orange, lemon, nutmeg',
      base_spirit: 'Neutral grain',
      infusion_method: 'Two-day botanical steep, then pot distillation',
      still_type: 'Copper pot',
      sugar_content: 'Lightly sweetened',
      style: 'Old Tom',
    },
  },

  // =========================================================================
  // SHOCHU
  // =========================================================================
  {
    name: 'Iichiko Saiten',
    category: 'Shochu',
    producer: 'Iichiko (Sanwa Shurui)',
    country: 'Japan',
    region: 'Ōita',
    abv: 43,
    price_cents: 1200,
    description:
      'Built specifically for cocktails at 43% — far above the usual 25% — from two-row barley and white koji.',
    tasting_notes: 'Toasted barley, banana, white flowers and a dry, clean finish.',
    specs: {
      base_ingredient: 'Two-row barley (mugi)',
      koji: 'White koji',
      fermentation: 'Two-stage, ~10 days',
      distillation_method: 'Atmospheric and vacuum blend',
      honkaku: 'Yes — single distilled',
      aging_length: 'Rested in tank',
      water_source: 'Ōita spring water',
    },
  },
  {
    name: 'Nankai Kokuto Shochu',
    category: 'Shochu',
    producer: 'Nankai',
    country: 'Japan',
    region: 'Amami Islands',
    abv: 40,
    price_cents: 1300,
    description:
      'Kokuto shochu — brown sugar based, and legally producible only on the Amami islands, and only when rice koji is used.',
    tasting_notes: 'Molasses, toasted almond, dried fig and a soft, gently sweet finish.',
    specs: {
      base_ingredient: 'Amami kokuto (brown sugar) with rice koji',
      koji: 'White koji on rice',
      fermentation: 'Two-stage',
      distillation_method: 'Atmospheric',
      honkaku: 'Yes',
      aging_length: '5 years in oak',
      water_source: 'Amami island water',
    },
  },
  {
    name: 'Kaikouzu Imo Shochu',
    category: 'Shochu',
    country: 'Japan',
    region: 'Kagoshima',
    abv: 25,
    price_cents: 1000,
    description:
      'Sweet potato shochu from Kagoshima, where the imo style is the local default and the potatoes are hand-trimmed.',
    tasting_notes: 'Roasted sweet potato, earth, violet and a savoury finish.',
    specs: {
      base_ingredient: 'Kogane Sengan sweet potato (imo)',
      koji: 'Black koji on rice',
      fermentation: 'Two-stage, ~10 days',
      distillation_method: 'Atmospheric',
      honkaku: 'Yes',
      water_source: 'Kagoshima volcanic spring water',
    },
  },

  // =========================================================================
  // AGAVE
  // =========================================================================
  {
    name: 'Del Maguey Chichicapa',
    category: 'Agave Spirits',
    subcategory: 'Mezcal',
    producer: 'Del Maguey',
    country: 'Mexico',
    region: 'San Baltazar Chichicapam, Oaxaca',
    abv: 46,
    price_cents: 1800,
    description:
      'One of the original single-village mezcals, and the bottle that taught a generation of bartenders that village matters more than brand.',
    tasting_notes: 'Wood smoke, green apple, mineral, black pepper and a long dry finish.',
    specs: {
      agave_type: 'Espadín (Agave angustifolia)',
      agave_age: '8–12 years',
      agave_origin: 'San Baltazar Chichicapam, 1,700m',
      cooking_method: 'Earthen pit, wood-fired, 3–5 days',
      milling: 'Horse-drawn tahona',
      fermentation_vessel: 'Open pine tanks',
      fermentation: 'Wild yeast, 7–10 days',
      water_source: 'Local spring',
      still_type: 'Small copper alembic',
      distillations: 'Twice',
      maestro: 'Faustino García Vásquez',
      nom: 'Certified mezcal, Oaxaca',
      aging_length: 'Unaged (joven)',
    },
  },
  {
    name: 'Rey Campero Jabalí',
    category: 'Agave Spirits',
    subcategory: 'Mezcal',
    producer: 'Rey Campero',
    country: 'Mexico',
    region: 'Candelaria Yegolé, Oaxaca',
    abv: 48.9,
    price_cents: 2600,
    description:
      'Jabalí is notoriously difficult — it foams violently in the still and many batches are lost. The ones that survive are extraordinary.',
    tasting_notes: 'Wet clay, cocoa, green herbs, tropical fruit and an intensely mineral finish.',
    specs: {
      agave_type: 'Jabalí (Agave convallis)',
      agave_age: '12–15 years, wild',
      agave_origin: 'Candelaria Yegolé, Oaxaca',
      cooking_method: 'Earthen pit with river rock and oak',
      milling: 'Tahona',
      fermentation_vessel: 'Open wooden vats',
      fermentation: 'Wild yeast, 8–15 days',
      still_type: 'Copper alembic',
      distillations: 'Twice',
      maestro: 'Romulo Sanchez Parada',
      nom: 'Certified mezcal',
      aging_length: 'Unaged',
    },
  },
  {
    name: 'Mezcal Vago Elote',
    category: 'Agave Spirits',
    subcategory: 'Mezcal',
    producer: 'Mezcal Vago',
    country: 'Mexico',
    region: 'Sola de Vega, Oaxaca',
    abv: 50.2,
    price_cents: 1900,
    description:
      'Espadín re-distilled with toasted local corn suspended in the still — a pechuga variant without the meat.',
    tasting_notes: 'Toasted corn, smoke, butter and a savoury, rounded finish.',
    specs: {
      agave_type: 'Espadín',
      agave_origin: 'Sola de Vega',
      cooking_method: 'Earthen pit',
      milling: 'Mechanical shredder',
      fermentation_vessel: 'Open wood',
      fermentation: 'Wild yeast',
      still_type: 'Copper alembic',
      distillations: 'Three — third with toasted corn',
      maestro: 'Aquilino García López',
      nom: 'Certified mezcal',
    },
  },
  {
    name: 'Fortaleza Blanco',
    category: 'Agave Spirits',
    subcategory: 'Tequila',
    producer: 'Tequila Fortaleza',
    country: 'Mexico',
    region: 'Tequila, Jalisco',
    abv: 40,
    price_cents: 1700,
    description:
      'Made the way the Sauza family made it before industrialisation: brick ovens, a stone tahona, open wooden fermenters, and copper pots.',
    tasting_notes: 'Cooked agave, olive brine, citrus, black pepper and a long herbal finish.',
    specs: {
      agave_type: 'Blue Weber (Agave tequilana)',
      agave_age: '7–9 years',
      agave_origin: 'Estate fields, Tequila valley',
      highlands_lowlands: 'Los Valles (lowlands)',
      cooking_method: 'Stone brick ovens, 36 hours',
      milling: 'Stone tahona',
      fermentation_vessel: 'Open pine tanks, with fibre',
      fermentation: 'Wild and cultured, 3–5 days',
      still_type: 'Copper pot',
      distillations: 'Twice',
      nom: 'NOM 1493',
      aging_length: 'Unaged',
    },
  },
  {
    name: 'G4 Blanco',
    category: 'Agave Spirits',
    subcategory: 'Tequila',
    producer: 'Destilería El Pandillo (G4)',
    country: 'Mexico',
    region: 'Jesús María, Jalisco',
    abv: 40,
    price_cents: 1600,
    description:
      'Felipe Camarena ferments with a blend of rainwater and deep well water, using a roller mill he built himself out of salvaged parts.',
    tasting_notes: 'Bright citrus, cooked agave, mineral and a soft peppery finish.',
    specs: {
      agave_type: 'Blue Weber',
      agave_origin: 'Los Altos, Jalisco',
      highlands_lowlands: 'Los Altos (highlands)',
      cooking_method: 'Stone brick ovens',
      milling: 'Custom roller mill ("Frankenstein")',
      fermentation_vessel: 'Stainless, with agave fibre',
      fermentation: 'Wild yeast, rainwater and well water',
      water_source: 'Rainwater + deep well',
      still_type: 'Copper pot',
      distillations: 'Twice',
      nom: 'NOM 1579',
      aging_length: 'Unaged',
    },
  },
  {
    name: 'Tapatio 110',
    category: 'Agave Spirits',
    subcategory: 'Tequila',
    producer: 'Tequila Tapatio',
    country: 'Mexico',
    region: 'Arandas, Jalisco',
    abv: 55,
    price_cents: 1800,
    description:
      'Overproof blanco from La Alteña, the Camarena family\'s own label — the tequila they keep for themselves.',
    tasting_notes: 'Enormous cooked agave, white pepper, citrus oil and a searing clean finish.',
    specs: {
      agave_type: 'Blue Weber',
      agave_origin: 'Estate fields, Arandas',
      highlands_lowlands: 'Los Altos',
      cooking_method: 'Brick ovens',
      milling: 'Roller mill with partial tahona',
      fermentation_vessel: 'Open wood',
      fermentation: 'Wild yeast, with fibre',
      still_type: 'Copper pot',
      distillations: 'Twice',
      nom: 'NOM 1139',
      aging_length: 'Unaged',
    },
  },
  {
    name: 'Sotol Por Siempre Blanco',
    category: 'Agave Spirits',
    subcategory: 'Sotol',
    producer: 'Sotol Por Siempre',
    country: 'Mexico',
    region: 'Chihuahua',
    abv: 45,
    price_cents: 1500,
    description:
      'Not agave at all — Dasylirion is a distinct genus, wild-harvested across the Chihuahuan desert and cooked in earthen pits.',
    tasting_notes: 'Green pepper, pine, wet earth and a bracing herbaceous finish.',
    specs: {
      dasylirion_species: 'Dasylirion wheeleri',
      agave_age: '12–15 years, wild harvested',
      agave_origin: 'Chihuahuan desert',
      cooking_method: 'Earthen pit, mesquite fired',
      milling: 'Hand mallet (mano)',
      fermentation_vessel: 'Open wood',
      fermentation: 'Wild yeast, 5–8 days',
      still_type: 'Small copper alembic',
      distillations: 'Twice',
      nom: 'Denominación de Origen Sotol',
    },
  },

  // =========================================================================
  // BRANDY
  // =========================================================================
  {
    name: 'Pierre Ferrand 1840 Original Formula',
    category: 'Brandy',
    subcategory: 'Cognac',
    producer: 'Maison Ferrand',
    country: 'France',
    region: 'Grande Champagne',
    abv: 45,
    price_cents: 1600,
    description:
      'Built from a 19th-century analysis of the cognac then used in bars, at the strength and richness that period cocktails were designed around.',
    tasting_notes: 'Dried apricot, walnut, honey, vanilla and a nutty rancio edge.',
    specs: {
      cru: 'Grande Champagne',
      grape_varieties: 'Ugni Blanc',
      still_type: 'Charentais copper alembic',
      lees: 'Yes — distilled on the lees',
      distillation_proof: '~140 proof',
      barrel_types: 'French oak, Limousin and Tronçais',
      aging_length: '~4–10 years',
      rancio: 'Emerging',
      additives: 'Minimal boisé',
    },
  },
  {
    name: 'Frapin VSOP Grande Champagne',
    category: 'Brandy',
    subcategory: 'Cognac',
    producer: 'Frapin',
    country: 'France',
    region: 'Grande Champagne',
    abv: 40,
    price_cents: 1900,
    description:
      'Single-estate Grande Champagne — grown, distilled, aged, and bottled by one family on one property.',
    tasting_notes: 'White flowers, pear, vanilla and a long chalky finish.',
    specs: {
      cru: 'Grande Champagne (1er cru)',
      grape_varieties: 'Ugni Blanc',
      still_type: 'Charentais alembic',
      lees: 'Yes',
      barrel_types: 'Limousin oak',
      aging_length: '~7 years',
      additives: 'None declared',
    },
  },
  {
    name: 'Château du Tariquet VSOP Bas-Armagnac',
    category: 'Brandy',
    subcategory: 'Armagnac',
    producer: 'Château du Tariquet',
    country: 'France',
    region: 'Bas-Armagnac',
    abv: 40,
    price_cents: 1500,
    description:
      'Continuous-still armagnac from the sandy fauve soils of Bas-Armagnac, aged in local black oak.',
    tasting_notes: 'Prune, toffee, orange peel and a rustic, gently tannic finish.',
    specs: {
      armagnac_region: 'Bas-Armagnac',
      grape_varieties: 'Ugni Blanc, Baco, Folle Blanche, Colombard',
      still_type: 'Alambic armagnacais (continuous)',
      distillation_proof: '~104–120 proof',
      barrel_types: 'Gascon black oak',
      aging_length: '~7 years',
      vintage_or_blend: 'Blend',
    },
  },
  {
    name: 'Massenez Poire Williams',
    category: 'Brandy',
    subcategory: 'Eau de Vie',
    producer: 'Massenez',
    country: 'France',
    region: 'Alsace',
    abv: 40,
    price_cents: 1400,
    description:
      'Roughly thirty pounds of Williams pears go into every bottle, and none of it ever sees wood.',
    tasting_notes: 'Pure ripe pear, floral, faintly almondy, with a clean dry finish.',
    specs: {
      fruit: 'Williams pear',
      fruit_ratio: '~14 kg per bottle',
      fermentation: 'Whole fruit, 4–6 weeks',
      still_type: 'Copper pot, bain-marie',
      distillation_proof: '~130 proof',
      aging_length: 'Rested in glass demijohns',
    },
  },
  {
    name: 'Clear Creek Apple Brandy 8 Year',
    category: 'Brandy',
    subcategory: 'Brandy Other',
    producer: 'Clear Creek Distillery',
    country: 'United States',
    region: 'Oregon',
    abv: 40,
    age_statement: '8 Years',
    price_cents: 1600,
    description:
      'Oregon apples distilled on Alsatian equipment and aged in French Limousin oak, in the Calvados idiom.',
    tasting_notes: 'Baked apple, cinnamon, oak and a dry orchard finish.',
    specs: {
      fruit: 'Golden Delicious and Newtown Pippin apples',
      fermentation: 'Whole fruit cider ferment',
      still_type: 'Holstein copper pot',
      barrel_types: 'French Limousin and Oregon oak',
      aging_length: '8 years',
    },
  },

  // =========================================================================
  // LIQUEURS
  // =========================================================================
  {
    name: 'Luxardo Maraschino Originale',
    category: 'Liqueurs',
    producer: 'Luxardo',
    country: 'Italy',
    abv: 32,
    price_cents: 1200,
    description:
      'Marasca cherries distilled whole — fruit, stems, leaves and pits together — then aged for two years in Finnish ash.',
    tasting_notes: 'Almond, cherry pit, floral, with a distinctly dry, nutty finish.',
    specs: {
      base_spirit: 'Marasca cherry distillate',
      flavor_source: 'Whole Marasca cherries with stems, leaves and pits',
      infusion_method: 'Maceration then triple pot distillation',
      sugar_content: '~250 g/L',
      aging_length: '2 years in Finnish ash vats',
    },
  },
  {
    name: 'Green Chartreuse',
    category: 'Liqueurs',
    producer: 'Chartreuse',
    country: 'France',
    abv: 55,
    price_cents: 1600,
    description:
      'One hundred and thirty botanicals to a 1605 manuscript, and the only liqueur whose green colour is entirely natural.',
    tasting_notes: 'Pine, mint, anise, honey and an enormous, evolving herbal finish.',
    specs: {
      base_spirit: 'Neutral, wine-derived',
      flavor_source: '130 botanicals, recipe known to two monks',
      infusion_method: 'Maceration and distillation, then cask ageing',
      sugar_content: '~250 g/L',
      aging_length: 'Aged in oak casks before bottling',
    },
  },
  {
    name: 'Cointreau',
    category: 'Liqueurs',
    producer: 'Cointreau',
    country: 'France',
    abv: 40,
    price_cents: 1100,
    description:
      'Sweet and bitter orange peels distilled separately in copper pots, then blended — the reference triple sec.',
    tasting_notes: 'Clean orange oil, faint bitterness, and a crisp dry finish.',
    specs: {
      base_spirit: 'Neutral beet',
      flavor_source: 'Sweet and bitter orange peel',
      infusion_method: 'Separate maceration and pot distillation, then blended',
      sugar_content: '~225 g/L',
    },
  },
  {
    name: 'Rothman & Winter Orchard Apricot',
    category: 'Liqueurs',
    producer: 'Rothman & Winter',
    country: 'Austria',
    abv: 24,
    price_cents: 1100,
    description:
      'Built on Klosterneuburger apricot eau-de-vie rather than neutral spirit, which is why it tastes like fruit rather than candy.',
    tasting_notes: 'Fresh apricot, stone fruit pit, honey and a tart finish.',
    specs: {
      base_spirit: 'Apricot eau-de-vie',
      flavor_source: 'Klosterneuburger apricots',
      infusion_method: 'Maceration in eau-de-vie',
      sugar_content: '~200 g/L',
    },
  },
  {
    name: 'Giffard Banane du Brésil',
    category: 'Liqueurs',
    producer: 'Giffard',
    country: 'France',
    abv: 25,
    price_cents: 1100,
    description:
      'A banana liqueur made from actual macerated fruit, which is rarer in this category than it should be.',
    tasting_notes: 'Ripe banana, vanilla, brown sugar and a soft tropical finish.',
    specs: {
      base_spirit: 'Neutral',
      flavor_source: 'Macerated Brazilian bananas',
      infusion_method: 'Cold maceration',
      sugar_content: '~200 g/L',
    },
  },

  // =========================================================================
  // AMARO
  // =========================================================================
  {
    name: 'Fernet-Branca',
    category: 'Amaro',
    producer: 'Fratelli Branca',
    country: 'Italy',
    abv: 39,
    price_cents: 1000,
    description:
      'Twenty-seven botanicals from four continents, aged a full year in Slavonian oak. The bartender\'s handshake.',
    tasting_notes: 'Menthol, saffron, myrrh, bitter root and a cold, cleansing finish.',
    specs: {
      amaro_style: 'Fernet',
      botanicals: 'Aloe, gentian, rhubarb, galanga, myrrh, chamomile, saffron, and 20 more',
      bittering_agent: 'Gentian, aloe, myrrh',
      base_spirit: 'Grape neutral',
      infusion_method: 'Maceration and infusion',
      sugar_content: '~50 g/L',
      aging_length: '12 months in Slavonian oak',
      origin_year: 1845,
    },
  },
  {
    name: 'Amaro Nonino Quintessentia',
    category: 'Amaro',
    producer: 'Nonino',
    country: 'Italy',
    region: 'Friuli',
    abv: 35,
    price_cents: 1500,
    description:
      'Built on aged grappa rather than neutral spirit, which gives it a weight and sweetness other amari cannot reach.',
    tasting_notes: 'Orange peel, caramel, gentian, apricot and a warm, elegant bitterness.',
    specs: {
      amaro_style: 'Alpino / grappa-based',
      botanicals: 'Gentian, rhubarb, bitter orange, quassia, saffron, tamarind',
      bittering_agent: 'Gentian, quassia',
      base_spirit: 'Aged ÙE grappa',
      infusion_method: 'Maceration',
      sugar_content: '~180 g/L',
      aging_length: 'Aged in ex-sherry and ex-Limousin barriques',
      origin_year: 1933,
    },
  },
  {
    name: 'Cynar',
    category: 'Amaro',
    country: 'Italy',
    abv: 16.5,
    price_cents: 900,
    description:
      'Thirteen botanicals with artichoke leaf at the centre — vegetal, low proof, and far more versatile than the label suggests.',
    tasting_notes: 'Artichoke, caramel, herbs and a vegetal, gently bitter finish.',
    specs: {
      amaro_style: 'Carciofo',
      botanicals: '13 herbs and plants, led by artichoke leaf',
      bittering_agent: 'Cynara (artichoke)',
      base_spirit: 'Neutral',
      infusion_method: 'Maceration',
      sugar_content: '~200 g/L',
      origin_year: 1952,
    },
  },
  {
    name: 'Cappelletti Sfumato Rabarbaro',
    category: 'Amaro',
    producer: 'Distilleria Pilzer (Sfumato)',
    country: 'Italy',
    region: 'Trentino',
    abv: 20,
    price_cents: 1300,
    description:
      'Smoked Chinese rhubarb root grown in the Alps. It tastes like a campfire that has been left out in the rain, in the best way.',
    tasting_notes: 'Smoke, rhubarb root, leather, tar and a dry, savoury bitterness.',
    specs: {
      amaro_style: 'Rabarbaro',
      botanicals: 'Smoked rhubarb root, alpine herbs',
      bittering_agent: 'Rheum palmatum (Chinese rhubarb)',
      base_spirit: 'Neutral',
      infusion_method: 'Maceration of smoke-dried root',
      sugar_content: '~180 g/L',
    },
  },
  {
    name: 'Braulio Amaro Alpino',
    category: 'Amaro',
    producer: 'Peloritana (Braulio)',
    country: 'Italy',
    region: 'Valtellina',
    abv: 21,
    price_cents: 1300,
    description:
      'Made in Bormio at 1,225 metres from herbs gathered in the surrounding Alps, then aged two years in Slavonian oak.',
    tasting_notes: 'Pine, mint, juniper, wormwood and a cold alpine finish.',
    specs: {
      amaro_style: 'Alpino',
      botanicals: 'Gentian, wormwood, yarrow, juniper, pine',
      bittering_agent: 'Gentian, wormwood',
      base_spirit: 'Neutral',
      infusion_method: 'Maceration',
      sugar_content: '~200 g/L',
      aging_length: '2 years in Slavonian oak',
      origin_year: 1875,
    },
  },

  // =========================================================================
  // APERITIVO
  // =========================================================================
  {
    name: 'Campari',
    category: 'Aperitivo',
    producer: 'Campari Group',
    country: 'Italy',
    abv: 24,
    price_cents: 1000,
    description:
      'The recipe has never been published. The colour came from cochineal insects until 2006, when it quietly switched to artificial dye.',
    tasting_notes: 'Bitter orange, rhubarb, cherry and a long, drying bitterness.',
    specs: {
      botanicals: 'Undisclosed — bitter orange, rhubarb, and aromatic herbs are established',
      bittering_agent: 'Bitter orange, cinchona',
      base_spirit: 'Neutral, water and alcohol infusion',
      sugar_content: '~240 g/L',
      coloring: 'Artificial (formerly carmine)',
      origin_year: 1860,
    },
  },
  {
    name: 'Aperol',
    category: 'Aperitivo',
    producer: 'Barbieri (Aperol)',
    country: 'Italy',
    abv: 11,
    price_cents: 900,
    description:
      'Deliberately low strength from the start, made for daytime drinking in Padua a century ago.',
    tasting_notes: 'Orange, rhubarb, gentian and a light, sweet-bitter finish.',
    specs: {
      botanicals: 'Bitter and sweet orange, gentian, rhubarb, cinchona',
      bittering_agent: 'Gentian, cinchona',
      base_spirit: 'Neutral',
      sugar_content: '~250 g/L',
      coloring: 'Artificial',
      origin_year: 1919,
    },
  },
  {
    name: 'Select Aperitivo',
    category: 'Aperitivo',
    country: 'Italy',
    region: 'Venice',
    abv: 17.5,
    price_cents: 1100,
    description:
      'The Venetian spritz base, built on rhubarb root and juniper — drier and more bitter than its Paduan cousin.',
    tasting_notes: 'Rhubarb, juniper, orange peel and a firm bitter finish.',
    specs: {
      botanicals: '30 botanicals including rhubarb root and juniper',
      bittering_agent: 'Rhubarb root',
      base_spirit: 'Neutral',
      sugar_content: '~220 g/L',
      origin_year: 1920,
    },
  },

  // =========================================================================
  // FORTIFIED & AROMATIZED WINES
  // =========================================================================
  {
    name: 'Carpano Antica Formula',
    category: 'Fortified & Aromatized Wines',
    producer: 'Carpano',
    country: 'Italy',
    region: 'Turin',
    abv: 16.5,
    price_cents: 1300,
    description:
      'A reconstruction of the 1786 original — the recipe that invented the category, and still the heaviest hand with vanilla in it.',
    tasting_notes: 'Vanilla, saffron, bitter orange, cocoa and a rich, sweet-bitter finish.',
    specs: {
      style: 'Vermouth di Torino rosso',
      grape_varieties: 'Italian white wine base',
      botanicals: 'Wormwood, vanilla, saffron, bitter orange, and others',
      fortifying_spirit: 'Grape neutral',
      aging_system: 'Static',
      sugar_content: '~160 g/L',
      serving: 'Refrigerate after opening; use within a month',
    },
  },
  {
    name: 'Dolin Blanc',
    category: 'Fortified & Aromatized Wines',
    producer: 'Dolin',
    country: 'France',
    region: 'Chambéry',
    abv: 16,
    price_cents: 1100,
    description:
      'The only vermouth with its own appellation, built on alpine botanicals and an unusually light touch.',
    tasting_notes: 'White flowers, honey, alpine herbs and a delicate, clean finish.',
    specs: {
      style: 'Vermouth de Chambéry blanc (AOC)',
      grape_varieties: 'Savoie white wine',
      botanicals: 'Alpine herbs from the Chambéry region',
      fortifying_spirit: 'Neutral grape',
      sugar_content: '~130 g/L',
      serving: 'Refrigerate after opening',
    },
  },
  {
    name: 'Lustau Los Arcos Amontillado',
    category: 'Fortified & Aromatized Wines',
    producer: 'Bodegas Lustau',
    country: 'Spain',
    region: 'Jerez',
    abv: 18.5,
    price_cents: 1200,
    description:
      'A sherry that lived twice — first under flor as a fino, then oxidatively once the flor died away.',
    tasting_notes: 'Hazelnut, saline, dried orange peel and a bone-dry finish.',
    specs: {
      style: 'Amontillado sherry',
      grape_varieties: 'Palomino Fino',
      fortifying_spirit: 'Grape spirit to 18.5%',
      aging_system: 'Solera y criaderas',
      aging_length: '~8 years, biological then oxidative',
      sugar_content: 'Dry — under 5 g/L',
      serving: 'Serve lightly chilled; finish within a week',
    },
  },
  {
    name: 'Cocchi Americano',
    category: 'Fortified & Aromatized Wines',
    producer: 'Cocchi',
    country: 'Italy',
    region: 'Piedmont',
    abv: 16.5,
    price_cents: 1100,
    description:
      'The nearest living relative of Kina Lillet, and the reason a period-correct Vesper is possible at all.',
    tasting_notes: 'Bitter orange, gentian, quinine and a light, sweetly bitter finish.',
    specs: {
      style: 'Aromatized wine / americano',
      grape_varieties: 'Moscato d\'Asti',
      botanicals: 'Cinchona, gentian, bitter orange peel',
      fortifying_spirit: 'Neutral grape',
      sugar_content: '~120 g/L',
      serving: 'Refrigerate after opening',
    },
  },
  {
    name: 'Taylor Fladgate 20 Year Tawny Port',
    category: 'Fortified & Aromatized Wines',
    producer: 'Taylor Fladgate',
    country: 'Portugal',
    region: 'Douro',
    abv: 20,
    age_statement: '20 Years',
    price_cents: 1600,
    description:
      'A blend whose average age is twenty years, aged oxidatively in seasoned oak pipes rather than in bottle.',
    tasting_notes: 'Walnut, dried fig, butterscotch and a long nutty finish.',
    specs: {
      style: 'Tawny Port',
      grape_varieties: 'Touriga Nacional, Touriga Franca, Tinta Roriz, and others',
      fortifying_spirit: 'Aguardente, 77% ABV',
      aging_system: 'Seasoned oak pipes, oxidative',
      aging_length: '20 year average',
      sugar_content: '~100 g/L',
      serving: 'Lightly chilled; keeps a month or more once open',
    },
  },

  // =========================================================================
  // BEER
  // =========================================================================
  {
    name: 'Cantillon Gueuze 100% Lambic Bio',
    kind: 'beer',
    category: 'Beer',
    producer: 'Brasserie Cantillon',
    country: 'Belgium',
    abv: 5,
    price_cents: 3200,
    description:
      'A blend of one, two, and three-year-old lambics, refermented in bottle. Spontaneously fermented in an open coolship in the Brussels attic air.',
    tasting_notes: 'Lemon, hay, barnyard, green apple and a bracing dry acidity.',
    specs: {
      style: 'Gueuze (blended lambic)',
      ibu: '~10',
      malt_bill: '65% pilsner malt, 35% unmalted wheat',
      hops: 'Aged hops, 3 years old, for preservative effect only',
      yeast: 'Spontaneous — wild Brussels microflora',
      fermentation: 'Open coolship, then oak barrels',
      barrel_types: 'Used oak wine and port barrels',
      aging_length: '1, 2 and 3 year lambics blended',
      package: '750ml bottle, bottle conditioned',
    },
  },
  {
    name: 'Rodenbach Grand Cru',
    kind: 'beer',
    category: 'Beer',
    producer: 'Brouwerij Rodenbach',
    country: 'Belgium',
    abv: 6,
    price_cents: 1600,
    description:
      'Two-thirds foeder-aged beer to one-third young — the inverse of the standard Rodenbach ratio, and far more intense for it.',
    tasting_notes: 'Sour cherry, balsamic, oak, and a sharp red-fruit acidity.',
    specs: {
      style: 'Flanders red ale',
      ibu: '~14',
      malt_bill: 'Pilsner, Munich, Vienna malt and maize',
      hops: 'Traditional Belgian',
      yeast: 'Mixed culture with lactobacillus',
      fermentation: 'Mixed, in standing oak foeders',
      barrel_types: 'Oak foeders, some over 150 years old',
      aging_length: '2 years for the aged portion',
      package: '750ml bottle',
    },
  },
  {
    name: 'Half Acre Daisy Cutter Pale Ale',
    kind: 'beer',
    category: 'Beer',
    producer: 'Half Acre Beer Company',
    country: 'United States',
    region: 'Chicago',
    abv: 5.2,
    price_cents: 800,
    description:
      'The Chicago pale ale, and one of the beers that set the template for the style in the Midwest.',
    tasting_notes: 'Grapefruit, pine, cracker malt and a crisp bitter finish.',
    specs: {
      style: 'American pale ale',
      ibu: '~65',
      malt_bill: 'Two-row and light crystal',
      hops: 'Columbus, Centennial, Simcoe, Amarillo',
      yeast: 'American ale',
      fermentation: 'Ale, then dry hopped',
      package: '16oz can, draft',
    },
  },
  {
    name: 'Pilsner Urquell',
    kind: 'beer',
    category: 'Beer',
    producer: 'Pilsner Urquell',
    country: 'Czech Republic',
    abv: 4.4,
    price_cents: 700,
    description:
      'The first pale lager ever brewed, in 1842, and still triple decoction mashed.',
    tasting_notes: 'Honeyed malt, Saaz spice, and a soft, lingering bitterness.',
    specs: {
      style: 'Czech pale lager',
      ibu: '~40',
      malt_bill: 'Moravian pilsner malt',
      hops: 'Saaz, three additions',
      yeast: 'H-strain lager yeast',
      fermentation: 'Triple decoction, open fermentation, cold lagering',
      package: 'Draft, 11.2oz bottle',
    },
  },

  // =========================================================================
  // WINE
  // =========================================================================
  {
    name: 'Domaine Tempier Bandol Rouge',
    kind: 'wine',
    category: 'Wine',
    producer: 'Domaine Tempier',
    country: 'France',
    region: 'Bandol',
    abv: 14,
    vintage: 2020,
    price_cents: 8500,
    description:
      'Old-vine Mourvèdre on limestone terraces above the Mediterranean, from the estate that made Bandol famous.',
    tasting_notes: 'Garrigue, black olive, leather, dark plum and a firm tannic frame.',
    specs: {
      grape_varieties: 'Mourvèdre (~75%), Grenache, Cinsault, Carignan',
      appellation: 'Bandol AOC',
      vineyard: 'Estate parcels, Le Plan du Castellet',
      soil: 'Limestone and clay terraces',
      farming: 'Organic',
      fermentation: 'Native yeast, concrete and steel',
      elevage: '18–20 months in large old oak foudres',
      serving: 'Decant an hour; drinks well for 20 years',
    },
  },
  {
    name: 'Pierre Péters Cuvée de Réserve Blanc de Blancs',
    kind: 'wine',
    category: 'Wine',
    producer: 'Pierre Péters',
    country: 'France',
    region: 'Champagne',
    abv: 12.5,
    price_cents: 9500,
    description:
      'Grand cru Chardonnay from the Côte des Blancs, built around a perpetual reserve started in 1988.',
    tasting_notes: 'Lemon curd, chalk, brioche and a long saline finish.',
    specs: {
      grape_varieties: '100% Chardonnay',
      appellation: 'Champagne Grand Cru',
      vineyard: 'Le Mesnil-sur-Oger, Oger, Avize, Cramant',
      soil: 'Chalk',
      farming: 'Sustainable',
      fermentation: 'Stainless steel, full malolactic',
      elevage: '3+ years on lees, perpetual reserve from 1988',
      dosage: '~7 g/L',
      serving: 'Serve at 10°C, not colder',
    },
  },
  {
    name: 'Ridge Lytton Springs',
    kind: 'wine',
    category: 'Wine',
    producer: 'Ridge Vineyards',
    country: 'United States',
    region: 'Dry Creek Valley, Sonoma',
    abv: 14.5,
    vintage: 2021,
    price_cents: 7500,
    description:
      'An old-vine field blend from Dry Creek, and one of the few American wines with full ingredient disclosure on the label.',
    tasting_notes: 'Blackberry, black pepper, cedar and a bright acid line.',
    specs: {
      grape_varieties: 'Zinfandel ~70%, Petite Sirah, Carignane, Mataro',
      appellation: 'Dry Creek Valley AVA',
      vineyard: 'Lytton Springs, vines to 120 years old',
      soil: 'Gravelly clay loam',
      farming: 'Organic certified',
      fermentation: 'Native yeast, open-top',
      elevage: '~14 months, 22% new American oak',
      production: '~10,000 cases',
    },
  },
  {
    name: 'Giuseppe Rinaldi Barolo Brunate',
    kind: 'wine',
    category: 'Wine',
    producer: 'Giuseppe Rinaldi',
    country: 'Italy',
    region: 'Barolo, Piedmont',
    abv: 14,
    vintage: 2019,
    price_cents: 24000,
    description:
      'Traditional Barolo from one of the great crus, farmed and made with almost nothing done to it.',
    tasting_notes: 'Rose, tar, sour cherry, iron and a very long, structured finish.',
    specs: {
      grape_varieties: '100% Nebbiolo',
      appellation: 'Barolo DOCG',
      vineyard: 'Brunate, La Morra',
      soil: 'Calcareous marl',
      farming: 'Organic in practice',
      fermentation: 'Native yeast, long submerged-cap maceration',
      elevage: '~3 years in large Slavonian oak botti',
      production: 'Very limited',
      serving: 'Needs 10+ years; decant several hours if opening young',
    },
  },

  // =========================================================================
  // 86'd — no longer stocked, still searchable in the 86 list
  // =========================================================================
  {
    name: 'Caroni 1996 17 Year',
    category: 'Rum',
    subcategory: 'Rum Other',
    country: 'Trinidad',
    abv: 55,
    age_statement: '17 Years',
    status: 'eightysixed',
    price_cents: 4500,
    description:
      'From the closed Caroni distillery in Trinidad, shuttered in 2002. Heavy, tarry, and finite — when the last casks are gone, that is the end of it.',
    tasting_notes: 'Tar, motor oil, dried fruit, tobacco and an enormous petrol-like finish.',
    specs: {
      base_material: 'Molasses',
      still_type: 'Column (heavy marque)',
      barrel_types: 'Ex-bourbon',
      aging_length: '17 years, partly tropical',
      additives: 'None',
    },
  },
  {
    name: 'Karuizawa 1981 Single Cask',
    category: 'Whiskey',
    subcategory: 'Japanese',
    country: 'Japan',
    region: 'Nagano',
    abv: 60.5,
    status: 'eightysixed',
    price_cents: 65000,
    description:
      'From a distillery that closed in 2000 and was demolished in 2016. The remaining casks are the entire supply that will ever exist.',
    tasting_notes: 'Dense sherry, dark chocolate, incense, leather and a colossal finish.',
    specs: {
      mash_bill: '100% Golden Promise barley',
      still_type: 'Small copper pot',
      barrel_types: 'Ex-sherry butt, single cask',
      aging_length: '30+ years',
      filtration: 'Non-chill filtered',
      jsla: 'Yes',
    },
  },
  {
    name: 'Chartreuse V.E.P. Green',
    category: 'Liqueurs',
    producer: 'Chartreuse',
    country: 'France',
    abv: 54,
    status: 'eightysixed',
    price_cents: 4000,
    description:
      'Vieillissement Exceptionnellement Prolongé — aged far longer than standard Green. Allocation has effectively ended.',
    tasting_notes: 'Deeper pine and honey, rounder, with an extraordinarily long finish.',
    specs: {
      base_spirit: 'Neutral',
      flavor_source: '130 botanicals',
      infusion_method: 'Maceration and distillation',
      aging_length: 'Exceptionally prolonged oak ageing',
    },
  },
  {
    name: 'Fortaleza Añejo',
    category: 'Agave Spirits',
    subcategory: 'Tequila',
    producer: 'Tequila Fortaleza',
    country: 'Mexico',
    region: 'Jalisco',
    abv: 40,
    status: 'eightysixed',
    price_cents: 3000,
    description:
      'Allocation ran out. Kept on the list so members can still find their notes and their order history.',
    tasting_notes: 'Cooked agave, caramel, oak and a long sweet-savoury finish.',
    specs: {
      agave_type: 'Blue Weber',
      cooking_method: 'Brick ovens',
      milling: 'Stone tahona',
      fermentation_vessel: 'Open pine',
      still_type: 'Copper pot',
      barrel_types: 'Ex-bourbon American oak',
      aging_length: '18 months',
      nom: 'NOM 1493',
    },
  },

  // =========================================================================
  // COCKTAILS — placeholder menu
  //
  // Dummy content, standing in until the real cocktail programme is written
  // up. Specs, prices and photography are all invented; swap them out from the
  // admin panel rather than editing this file once the bar is running.
  // =========================================================================
  {
    name: 'The Trelawny',
    kind: 'cocktail',
    category: 'Cocktails',
    subcategory: 'House Originals',
    price_cents: 1900,
    hero_image_url: '/images/space/subourbon-bar.jpg',
    description:
      'Our answer to the daiquiri, built on high-ester Jamaican pot still rum and stretched out with a little sherry so the funk has somewhere to land.',
    tasting_notes: 'Overripe banana, lime oil and salted almond, with a dry, faintly briny finish.',
    specs: {
      build: '1.5 oz Hampden Estate 8 Year · 0.5 oz fino sherry · 0.75 oz lime · 0.5 oz demerara syrup · 2 dashes saline',
      method: 'Shaken, fine strained',
      base_spirit: 'Jamaican rum',
      glassware: 'Coupe',
      ice: 'None — served up',
      garnish: 'Lime leaf',
      creator: 'Bar team, 2026',
    },
  },
  {
    name: 'Executive Order',
    kind: 'cocktail',
    category: 'Cocktails',
    subcategory: 'House Originals',
    price_cents: 2100,
    hero_image_url: '/images/space/subourbon-executive-bottles.jpg',
    description:
      'A split-base old fashioned that leans on the vault. Bourbon for the spine, aged agave for the smoke, and a bar spoon of amaro to keep it from getting comfortable.',
    tasting_notes: 'Baking spice and cooked agave up front, then cocoa, orange peel and a long bitter tail.',
    specs: {
      build: '1.5 oz bourbon · 0.5 oz añejo tequila · 0.25 oz Amaro Nonino · 1 tsp demerara · Angostura',
      method: 'Stirred',
      base_spirit: 'Bourbon & agave',
      glassware: 'Rocks',
      ice: 'Single large cube',
      garnish: 'Expressed orange peel',
      batched: 'Yes — spirits pre-batched, bittered to order',
      creator: 'Bar team, 2026',
    },
  },
  {
    name: 'Vieux Carré',
    kind: 'cocktail',
    category: 'Cocktails',
    subcategory: 'Stirred',
    price_cents: 1800,
    hero_image_url: '/images/space/subourbon-vault.jpg',
    description:
      'The Hotel Monteleone\'s house drink, and still the most complete argument for stirring two spirits together. Rye and cognac share the base; Bénédictine does the reconciling.',
    tasting_notes: 'Honeyed herbs, dried cherry and rye spice, with a soft, sweet-bitter middle.',
    specs: {
      build: '1 oz rye · 1 oz cognac · 1 oz sweet vermouth · 1 tsp Bénédictine · Peychaud\'s & Angostura',
      method: 'Stirred',
      base_spirit: 'Rye & cognac',
      glassware: 'Rocks',
      ice: 'Single large cube',
      garnish: 'Lemon peel',
      origin: 'New Orleans, 1938',
      creator: 'Walter Bergeron',
    },
  },
  {
    name: 'Hanky Panky',
    kind: 'cocktail',
    category: 'Cocktails',
    subcategory: 'Stirred',
    price_cents: 1700,
    hero_image_url: '/images/space/subourbon-bar.jpg',
    description:
      'A sweet martini with two dashes of Fernet-Branca in it — which sounds like a rounding error and is in fact the whole drink.',
    tasting_notes: 'Vermouth sweetness cut clean by menthol and bitter root. Short, dry finish.',
    specs: {
      build: '1.5 oz London dry gin · 1.5 oz sweet vermouth · 2 dashes Fernet-Branca',
      method: 'Stirred',
      base_spirit: 'Gin',
      glassware: 'Coupe',
      ice: 'None — served up',
      garnish: 'Expressed orange peel',
      origin: 'The Savoy, London, c. 1903',
      creator: 'Ada Coleman',
    },
  },
  {
    name: 'Paper Plane',
    kind: 'cocktail',
    category: 'Cocktails',
    subcategory: 'Shaken',
    price_cents: 1800,
    hero_image_url: '/images/space/subourbon-founders-wide.jpg',
    description:
      'Four equal parts, no wasted motion. The modern bar\'s favourite equal-parts drink, and the one that made Amaro Nonino a house staple.',
    tasting_notes: 'Bright citrus over orange-peel bitterness, bourbon warmth underneath.',
    specs: {
      build: '0.75 oz bourbon · 0.75 oz Amaro Nonino · 0.75 oz Aperol · 0.75 oz lemon',
      method: 'Shaken, fine strained',
      base_spirit: 'Bourbon',
      glassware: 'Coupe',
      ice: 'None — served up',
      garnish: 'None',
      origin: 'Chicago, 2008',
      creator: 'Sam Ross',
    },
  },
  {
    name: 'Naked & Famous',
    kind: 'cocktail',
    category: 'Cocktails',
    subcategory: 'Shaken',
    price_cents: 1900,
    hero_image_url: '/images/space/subourbon-vault.jpg',
    description:
      'The Last Word, rebuilt around mezcal and Yellow Chartreuse. Smoke and bitterness held in balance by a lot of lime.',
    tasting_notes: 'Woodsmoke, grapefruit pith and alpine herbs. Long and dry.',
    specs: {
      build: '0.75 oz mezcal · 0.75 oz Yellow Chartreuse · 0.75 oz Aperol · 0.75 oz lime',
      method: 'Shaken, fine strained',
      base_spirit: 'Mezcal',
      glassware: 'Coupe',
      ice: 'None — served up',
      garnish: 'None',
      origin: 'New York, 2011',
      creator: 'Joaquín Simó',
    },
  },
  {
    name: 'Improved Ranch Water',
    kind: 'cocktail',
    category: 'Cocktails',
    subcategory: 'Highballs & Spritz',
    price_cents: 1600,
    hero_image_url: '/images/space/subourbon-bar.jpg',
    description:
      'Blanco tequila, lime and Topo Chico, with a quarter ounce of sotol to give it a green, vegetal edge the original never had.',
    tasting_notes: 'Crisp and saline, with cucumber skin and white pepper on the finish.',
    specs: {
      build: '1.5 oz blanco tequila · 0.25 oz sotol · 0.75 oz lime · pinch of salt · Topo Chico',
      method: 'Built in glass',
      base_spirit: 'Tequila',
      glassware: 'Highball',
      ice: 'Collins spear',
      garnish: 'Lime wedge',
    },
  },
  {
    name: 'Amaro Spritz',
    kind: 'cocktail',
    category: 'Cocktails',
    subcategory: 'Highballs & Spritz',
    price_cents: 1500,
    hero_image_url: '/images/space/subourbon-founders-wide.jpg',
    description:
      'Whatever amaro is open and interesting, lengthened with prosecco and soda. Ask what is pouring — it moves.',
    tasting_notes: 'Depends entirely on the bottle. Always bitter, always low-proof, always cold.',
    specs: {
      build: '2 oz amaro of the day · 3 oz prosecco · 1 oz soda',
      method: 'Built in glass',
      base_spirit: 'Amaro',
      glassware: 'Wine glass',
      ice: 'Cubed, to the rim',
      garnish: 'Orange half-wheel',
      batched: 'No — built to order',
    },
  },
  {
    name: 'Garden Gate',
    kind: 'cocktail',
    category: 'Cocktails',
    subcategory: 'Zero Proof',
    price_cents: 1200,
    hero_image_url: '/images/space/subourbon-vault.jpg',
    description:
      'A zero-proof drink built like a real one: verjus for acid, a saline solution for length, and a snap pea shrub that does the work a spirit normally would.',
    tasting_notes: 'Green and savoury, with cucumber, celery leaf and a clean tart finish.',
    specs: {
      build: '1.5 oz snap pea shrub · 1 oz verjus blanc · 0.5 oz honey · 3 dashes saline · soda',
      method: 'Shaken, topped',
      base_spirit: 'None',
      glassware: 'Highball',
      ice: 'Collins spear',
      garnish: 'Celery leaf',
      creator: 'Bar team, 2026',
    },
  },
]
